# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Alvis-Convert
version:      0.2
version_from: lib/Alvis/Convert.pm
installdirs:  site
requires:
    Compress::Zlib:                0
    Cwd:                           0
    Data::Dumper:                  0
    Digest::MD5:                   0
    Encode:                        0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Type:                    0
    Getopt::Long:                  0
    HTML::Encoding:                0
    HTTP::Headers::Util:           0
    IO::Handle:                    0
    Parse::MediaWikiDump:          0
    Pod::Usage:                    0
    POSIX:                         0
    Time::HiRes:                   0
    XML::LibXML:                   0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
